package com.example.eduhub20.data.ai

import com.example.eduhub20.data.model.AiGeneratedNote
import com.example.eduhub20.data.model.LectureNote
import com.example.eduhub20.data.model.Quiz
import com.example.eduhub20.data.model.QuizQuestion
import kotlinx.coroutines.delay
import java.util.UUID

object EduHubAiGenerator {

    /**
     * Generates a structured AI study note from raw lecture notes or PDF content.
     */
    suspend fun generateNoteSummary(lectureNote: LectureNote): AiGeneratedNote {
        // Simulate AI reasoning and parsing
        delay(1200)

        val takeaways = mutableListOf<String>()
        val terminology = mutableMapOf<String, String>()

        if (lectureNote.chapterTitle.contains("Mobile", ignoreCase = true) ||
            lectureNote.rawContent.contains("Mobile", ignoreCase = true)
        ) {
            takeaways.add("Mobile app development is the process of creating software for handheld devices like smartphones and tablets.")
            takeaways.add("The two major platforms are iOS (Apple) and Android (Google), requiring different programming languages.")
            takeaways.add("Cross-platform development allows code reuse using frameworks like React Native or Flutter.")
            takeaways.add("Native development offers the highest hardware performance and access to platform-specific APIs.")

            terminology["IDE"] = "Integrated Development Environment"
            terminology["SDK"] = "Software Development Kit"
            terminology["API"] = "Application Programming Interface"
            terminology["UI/UX"] = "User Interface / User Experience"
            terminology["Jetpack Compose"] = "Modern declarative UI toolkit for native Android apps"
        } else if (lectureNote.chapterTitle.contains("Calculus", ignoreCase = true) ||
            lectureNote.courseTitle.contains("Calculus", ignoreCase = true)
        ) {
            takeaways.add("Calculus models rates of change (differentiation) and accumulation of quantities (integration).")
            takeaways.add("Matrix algebra enables efficient multi-dimensional transformations and transformations in computer graphics.")
            takeaways.add("Eigenvalues and eigenvectors identify fundamental invariant directions in linear transformations.")

            terminology["Derivative"] = "Instantaneous rate of change of a function with respect to a variable"
            terminology["Integral"] = "Continuous summation of infinitesimals representing area or volume"
            terminology["Matrix"] = "Rectangular array of numbers representing a linear map"
        } else {
            // General AI Extraction
            takeaways.add("Core concept breakdown of .")
            takeaways.add("Foundational principles established in .")
            takeaways.add("Practical applications and exam preparation highlights.")

            terminology["Concept"] = "Key foundational principle covered in the lecture"
            terminology["Methodology"] = "Systematic approach applied to solve core domain problems"
        }

        return AiGeneratedNote(
            id = UUID.randomUUID().toString(),
            noteId = lectureNote.id,
            title = lectureNote.chapterTitle,
            keyTakeaways = takeaways,
            keyTerminology = terminology,
            summary = "Summary generated by EduHub AI for . Covers key operational paradigms, terminology, and revision points from lecture slides.",
            originalSlidesUrl = "https://eduhub.edu.my/slides/.pdf"
        )
    }

    /**
     * Automatically creates an interactive multi-question quiz based on generated study notes.
     */
    suspend fun generateQuizFromNote(note: AiGeneratedNote, courseCode: String): Quiz {
        // Simulate AI question generation
        delay(1400)

        val questions = mutableListOf<QuizQuestion>()

        if (courseCode.contains("3353") || note.title.contains("Mobile", ignoreCase = true)) {
            questions.add(
                QuizQuestion(
                    questionNumber = 1,
                    totalQuestions = 10,
                    questionText = "According to mobile application architectures, which app type typically has the highest development cost and platform-specific code requirement?",
                    tableOrDiagram = """
| App Type   | Code Reuse | Performance | Dev Cost |
|------------|------------|-------------|----------|
| Native     | Low        | High        | High     |
| Hybrid     | High       | Medium      | Medium   |
| Mobile Web | High       | Low         | Low      |
                    """.trimIndent(),
                    options = listOf(
                        "A) Native",
                        "B) Hybrid",
                        "C) Mobile Web",
                        "D) All are equal"
                    ),
                    correctOptionIndex = 0,
                    reviewExplanation = "You selected Native! Native apps have the highest development cost (marked as 'High'), while Hybrid and Mobile Web are both lower due to separate codebases for iOS and Android teams."
                )
            )

            questions.add(
                QuizQuestion(
                    questionNumber = 2,
                    totalQuestions = 10,
                    questionText = "Which declarative UI framework is officially recommended by Google for modern Android application development in Kotlin?",
                    tableOrDiagram = null,
                    options = listOf(
                        "A) Flutter",
                        "B) Jetpack Compose",
                        "C) React Native",
                        "D) XML View Binding"
                    ),
                    correctOptionIndex = 1,
                    reviewExplanation = "Jetpack Compose is Google's modern declarative toolkit for building native Android UI in Kotlin, replacing traditional XML layouts."
                )
            )

            questions.add(
                QuizQuestion(
                    questionNumber = 3,
                    totalQuestions = 10,
                    questionText = "What does the abbreviation 'SDK' stand for in software engineering?",
                    tableOrDiagram = null,
                    options = listOf(
                        "A) Software Development Kit",
                        "B) System Developer Kernel",
                        "C) Standard Data Key",
                        "D) Structured Design Kit"
                    ),
                    correctOptionIndex = 0,
                    reviewExplanation = "SDK stands for Software Development Kit, providing libraries, documentation, and tools needed to build apps for a platform."
                )
            )
        } else {
            questions.add(
                QuizQuestion(
                    questionNumber = 1,
                    totalQuestions = 5,
                    questionText = "What is the primary objective of studying ?",
                    tableOrDiagram = null,
                    options = listOf(
                        "A) Mastering foundational concepts and applications",
                        "B) Memorizing syntax only",
                        "C) Skipping practical assignments",
                        "D) None of the above"
                    ),
                    correctOptionIndex = 0,
                    reviewExplanation = "Foundational concepts and practical applications form the core learning outcomes of ."
                )
            )
        }

        return Quiz(
            id = UUID.randomUUID().toString(),
            noteId = note.id,
            courseCode = courseCode,
            title = " Revision Quiz",
            questions = questions,
            isCompleted = false,
            scorePercentage = 0
        )
    }
}